import React from 'react';

export function ArticleSection() {
  return (
    <article className="prose prose-slate max-w-none bg-white p-8 rounded-2xl shadow-sm border border-slate-100">
      <h2 className="text-3xl font-bold text-slate-800 mb-6">Mastering GSTR-2B Reconciliation: The Ultimate Guide for Indian Businesses (2025)</h2>
      
      <p className="lead text-lg text-slate-600 mb-6">
        Reconciling your purchase register with <strong>GSTR-2B</strong> is critical for claiming 100% accurate Input Tax Credit (ITC). 
        With the GST laws in India becoming stricter, manual matching is no longer feasible. This guide explains why you need an 
        automated <strong>GSTR-2B Reconciliation Tool</strong> and how to use it effectively.
      </p>

      <h3 className="text-xl font-bold text-slate-800 mt-8 mb-4">What is GSTR-2B and Why is Reconciliation Mandatory?</h3>
      <p>
        <strong>GSTR-2B</strong> is an auto-drafted ITC statement generated by the GST Portal for every recipient. 
        Unlike GSTR-2A, the GSTR-2B is static for a month, making it the definitive document for claiming ITC.
        Per <strong>Rule 36(4) of CGST Rules</strong>, you can only claim ITC if the invoice appears in your GSTR-2B. 
        Therefore, reconciling your internal <em>Purchase Register (Excel/Tally)</em> with the <em>GSTR-2B JSON</em> is mandatory 
        to avoid notices and interest penalties.
      </p>

      <h3 className="text-xl font-bold text-slate-800 mt-8 mb-4">Common Challenges in GST Reconciliation</h3>
      <ul className="list-disc pl-5 space-y-2 text-slate-600">
        <li><strong>Invoice Number Mismatches:</strong> Suppliers often format invoice numbers differently (e.g., "INV/23-24/001" vs "001"). Our tool uses smart cleaning algorithms to match these automatically.</li>
        <li><strong>Date Differences:</strong> Posting dates in books often differ from the actual invoice date.</li>
        <li><strong>Rounding Off Errors:</strong> Small differences in decimal places can cause rows to show as "Mismatch". A tolerance limit (e.g., ₹2) helps solve this.</li>
        <li><strong>Volume of Data:</strong> Manually checking thousands of rows in Excel is prone to human error and extremely time-consuming.</li>
      </ul>

      <h3 className="text-xl font-bold text-slate-800 mt-8 mb-4">Why Use This Free GSTR-2B Reconciliation Tool?</h3>
      <p>
        We built this tool specifically for CAs, Tax Practitioners, and Accountants in <strong>Gujarat, Mumbai, Delhi, and across India</strong>. 
        Unlike other paid software, this tool is:
      </p>
      <ul className="list-disc pl-5 space-y-2 text-slate-600 mt-4">
        <li><strong>100% Free & Unlimited:</strong> No hidden charges, no row limits. Reconcile 10,000+ invoices in seconds.</li>
        <li><strong>Secure & Private:</strong> It runs completely in your browser. Your sensitive financial data <strong>never leaves your computer</strong>.</li>
        <li><strong>Smart Matching Logic:</strong> Automatically handles common typos, financial year prefixes, and leading zeros.</li>
        <li><strong>Instant Excel Reports:</strong> Download a color-coded reconciliation report ready for audit.</li>
      </ul>

      <h3 className="text-xl font-bold text-slate-800 mt-8 mb-4">How to Reconcile GSTR-2B in 3 Steps</h3>
      <ol className="list-decimal pl-5 space-y-2 text-slate-600">
        <li><strong>Download GSTR-2B JSON:</strong> Log in to the GST Portal, go to Returns Dashboard &gt; Select Month &gt; Download GSTR-2B JSON.</li>
        <li><strong>Prepare Purchase Register:</strong> Export your purchase data from Tally, Zoho, or Busy into an Excel file.</li>
        <li><strong>Upload & Match:</strong> Drag and drop both files into the tool above. Click "Start Reconciliation" to see the magic!</li>
      </ol>

      <div className="bg-blue-50 border-l-4 border-blue-500 p-4 mt-8">
        <p className="font-semibold text-blue-800">Pro Tip for Accountants:</p>
        <p className="text-blue-700 text-sm mt-1">
          Always focus on the "Missing in GSTR-2B" tab first. These are the invoices where you have paid GST to the supplier, 
          but they haven't filed their return. Follow up with these vendors immediately to save your working capital!
        </p>
      </div>
    </article>
  );
}
